<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('products')->delete();

        DB::table('products')->insert(array(
array('quantity' => 10, 'productName' => 'Linksys AC1900 Gigabit Range Extender / WiFi Booster / Repeater MU-MIMO (Max Stream RE7000)', 'category' => 'PC & Accessories', 'brand' => 'Linksys', 'price' => '129.99', 'image' => '52P5piGkUM.jpg', 'description' => '<ul><li>Eliminates Wi-Fi dead zones and boost Next-Gen AC Wi-Fi in and around your home</li><li>Works with all Wi-Fi Routers and Multi-User MIMO Routers</li><li>Simple setup with Push Button Connect and Spot Finder Technology for optimal placement and performance</li><li>Advanced dual-band Wi-Fi Speeds up to AC1900+ (N300+AC1733)</li><li>Expand Wi-Fi coverage up to 10,000 square feet</li><li>Cross-Band and Beamforming Technologies work to optimize Wi-Fi connections</li><li>Gain enhanced wired speeds for a Smart TV, gaming console, Blu-ray Disc player or other Wi-Fi device using the Gigabit Ethernet port</li><li>Can also work in Access Point mode for an expanded Wi-Fi network</li></ul>', 'available' => true),
array('quantity' => 10, 'productName' => 'Linksys AC1750 Dual-Band Smart Wireless Router with MU-MIMO (Max Stream EA7300)', 'category' => 'PC & Accessories', 'brand' => 'Linksys', 'price' => '129.99', 'image' => 'z2kOEpanGU.jpg', 'description' => '<ul><li>Next-Gen AC Wi-Fi - Multi-User MIMO technology - is like having a dedicated router for multiple devices on your home Wi-Fi</li><li>Combined dual-band speeds up to 1.7 Gbps for powerful Wi-Fi performance</li><li>Beamforming technology focuses Wi-Fi single to each device on your network</li><li>Featuring a new look, Smart Wi-Fi app provides parental controls, guest passwords and much more to fully manage your home Wi-Fi from a mobile device anytime, anywhere</li></ul>', 'available' => true),
array('quantity' => 10, 'productName' => 'SanDisk Ultra 64GB Dual Drive m3.0 for Android Devices and Computers (SDDD3-064G-G46)', 'category' => 'PC & Accessories', 'brand' => 'SanDisk', 'price' => '23.49', 'image' => 'Q4ckZEH1Q2.jpg', 'description' => '<ul><li>Free up space on your OTG-enabled Android phone</li><li>Back up your mobile photos, videos and contacts</li><li>Retractable design with dual micro-USB and USB 3.0 connectors</li><li>High-speed USB 3.0 performance with up to 150MB/s file transfer from drive to computer</li><li>SanDisk Memory Zone application (available on Google Play) lets you easily manage your photos and videos</li></ul>', 'available' => true),
array('quantity' => 10, 'productName' => 'Omars 32GB USB 3.0 Flash Drive with Lightning Connector, Gold', 'category' => 'PC & Accessories', 'brand' => 'Omars', 'price' => '33.99', 'image' => 'oSXVcebsLq.jpg', 'description' => '<ul><li>AMAZING SUPERSPEED USB 3.0 FILE TRANSFERS: Transfer photos/music/movies to and from your computer at up to 80 MB/s reading and 35 MB/s writing speed.You can transfer a 3GB HD video or Photos in less than one minute.</li><li>CONVENIENT EXTENDED LIGHTNING CONNECTOR BASE: With authentic Apple MFi certification, 100% compatible with Lightning iPhone and iPad, extra 2mm extension means the connector works with most of thick cases without having to take them off.</li><li>USER-FRIENDLY STREAMING APP: The free Witstick app supports all major video and music formats so you can stream directly from the drive, saving you precious space and time.Playback the videos/music directly from external memory stick. Backup and restore your contact list at one click.</li><li>INSTANT PLUG-AND-PLAY STORAGE: Instantly add 32GB of storage space to your iPhone / iPad - Let you free up memory on your mobile devices without using a cable or iCloud.Take more photos, enjoy longer videos, and do more of everything you love. Please Note: 1) Please remove your iPhone case first if necessary. 2) You cannot transfer media files downloaded from iTunes or other 3rd party apps, as these files are DRM (Digital Rights Management) protected.</li><li>QUALITY GUARANTEED By CE, FCC & MFi: Inside each lightning connector is a tiny authentication chip that tells your device it\'s Apple MFI Certified. This is important because non-certified, or knock-off lightning connectors can be very dangerous to your device,which can often times get extremely hot, cause damage to your phone, and even render it completely fried and useless.12 Months Worry-free Warranty & dedicated email customer support.</li></ul>', 'available' => true),
array('quantity' => 10, 'productName' => 'MSI VR Ready GT72VR Dominator-071 17.3\" G-SYNC Hardcore Gaming Laptop GTX 1060 i7-6700HQ 12GB 128GB M.2 SATA + 1TB Windows 10', 'category' => 'PC & Accessories', 'brand' => 'MSI', 'price' => '1549.00', 'image' => 'mHoy1p8tHL.jpg', 'description' => '<ul><li>Display: 17.3\" Full HD Non Reflection 1920x1080 | Operating System: Windows 10</li><li>Processor: Intel Core i7-6700HQ Quad Core Processor (2.6-3.5GHz)</li><li>Graphics Card: NVIDIA\'s Latest GeForce GTX 1060 6G GDDR5</li><li>RAM: 12GB (8GB + 4GB) DDR4 2400MHz | Hard Drive: 128GB M.2 SATA SSD + 1TB (7200rpm)</li><li>Special features: *Amazon Exclusive Model | VR READY | G-Sync | Steel Series Full-Color Backlight Keyboard w/ Anti-Ghost Key + Silver Lining | Killer Gaming Network E2400 | Metal Build, Refer user manual below</li></ul>', 'available' => true),
array('quantity' => 10, 'productName' => 'NETGEAR ReadyNAS 526X Network Attached Storage 6 Bay Diskless (RN526X00-100NES)', 'category' => 'PC & Accessories', 'brand' => 'NETGEAR', 'price' => '1399.99', 'image' => 'dOcFj7dCFQ.jpg', 'description' => '<ul><li>5 levels of superior data protection: X-RAID, Unlimited Snapshots, Bit rot protection, anti-virus and offsite replication</li><li>State-of-the-art BTRFS file system allows for unmatched snapshot efficiency and data integrity versus traditional EXT4 based systems</li><li>\"VMware Ready\" for Storage certification ensures interoperability in vSphere 6 environments, works with Microsoft Hyper-V and Citrix</li><li>High performance Dual core 2.2GHz Intel® D-1508 server processor 4GB DDR4 ECC Memory with 2 x 10 Gigabit copper Ethernet ports</li><li>6 bays support up to 60TB of storage, up to 110TB with optional EDA500 expansion chassis; tool-less drive trays make installation a breeze</li></ul>', 'available' => true),
array('quantity' => 10, 'productName' => 'SanDisk SSD PLUS 960GB Solid State Drive (SDSSDA-960GB-G26)', 'category' => 'PC & Accessories', 'brand' => 'SanDisk', 'price' => '249.99', 'image' => 'IgzOaIl4Q4.jpg', 'description' => '<ul><li>Easy upgrade for faster Boot-up, shutdown, application load and response</li><li>Boosts burst write performance, making it ideal for typical PC</li><li>The perfect balance of performance and reliability</li><li>Read/write speeds of up to 535MB/s/450MB/s</li><li>Shock-resistant for proven durability if you drop your computer</li></ul>', 'available' => true),
array('quantity' => 10, 'productName' => 'HP Notebook 15-ay011nr 15.6-Inch Laptop (6th Gen Intel Core i5-6200U Processor, 8GB DDR3L SDRAM, 1TB HDD, Windows 10), Silver', 'category' => 'PC & Accessories', 'brand' => 'HP', 'price' => '459.99', 'image' => 'XgjsSvyzVa.jpg', 'description' => '<ul><li>Intel® Core(TM) i5-6200U Processor 2.3GHz with turbo boost up to 2.8GHz</li><li>8GB DDR3L-SDRAM Memory</li><li>More productive. Windows 10 is the best for bringing ideas forward and getting things done.</li><li>1TB 5400RPM Hard Drive, Super-Multi DVD Burner</li><li>15.6\" diagonal Full HD SVA antiglare WLED-backlit (1920 x 1080)</li></ul>', 'available' => true),
array('quantity' => 10, 'productName' => 'Acer Chromebook R 11 Convertible, 11.6-Inch HD Touch, Intel Celeron N3150, 4GB DDR3L, 32GB, Chrome, CB5-132T-C1LK', 'category' => 'PC & Accessories', 'brand' => 'Acer', 'price' => '299.99', 'image' => 'NUVqVV1z13.jpg', 'description' => '<ul><li>Intel Celeron N3150 Quad-Core Processor 1.6GHz with Intel Burst Technology up to 2.08GHz</li><li>11.6\" HD Widescreen LED-backlit Display, Multi-touch screen, supporting 10 finger touch</li><li>4GB DDR3L Onboard Memory, 32GB Internal Storage</li><li>Up to 10-hours Battery Life</li></ul>', 'available' => true),
array('quantity' => 10, 'productName' => 'ROG Strix GL502VM 15.6\" G-SYNC VR Ready Thin and Light Gaming Laptop NVIDIA GTX 1060 6GB Intel Core i7-6700HQ 16GB DDR4 1TB 7200RPM HDD', 'category' => 'PC & Accessories', 'brand' => 'Asus', 'price' => '1399.00', 'image' => 'muKCmfq8WY.jpg', 'description' => '<ul><li>6th-generation Intel® CoreTM i7 quad-core processor and with a discrete NVIDIA® GeForce® GTXTM 1060 graphics with 6GB GDDR5</li><li>15-inch G-SYNC panel with wide 160° viewing angles and Windows 10 pre-installed</li><li>16GB DDR4 RAM and 1TB HDD for fast performance and large storage capacity. Red-backlit scissor-switch keys offering 1.6mm of travel distance for tactile keystrokes</li><li>802.11ac 2x2 WiFi, Bluetooth 4.0, USB Type-C Gen 2, Up to 5 hours battery life. 0.94 inches thick and 4.8 pounds for superior portability</li><li>** VERY IMPORTANT ** Please Note: Kindly refer the User Manual before use.</li></ul>', 'available' => true),
array('quantity' => 10, 'productName' => 'MSI GeForce GTX 1080 Founders Edition (GEFORCE GTX 1080 Founders Edition)', 'category' => 'PC & Accessories', 'brand' => 'MSI', 'price' => '647.82', 'image' => 'He2sZ6H6GO.jpg', 'description' => '<ul><li>New Pascal Architecture</li><li>8 GB 256-bit GDDR5X</li><li>Virtual Reality Ready</li><li>4K Gaming</li><li>1x Dual-link DVI-I, 3x DisplayPort (version 1.4), 1x HDMI</li></ul>', 'available' => true),
array('quantity' => 10, 'productName' => 'ASUS VG245H 24\" 1080p 75Hz 1ms Dual HDMI Eye Care Console Gaming Monitor', 'category' => 'PC & Accessories', 'brand' => 'Asus', 'price' => '189.99', 'image' => 'wOOs6Fq9Dw.jpg', 'description' => '<ul><li>1ms response time featuring ASUS GameFast Input Technology and dual HDMI ports for a smooth console gaming experience</li><li>ASUS Eye Care technology with flicker-free and blue light filter to minimize eye fatigue</li><li>Ergonomic stand with full height/tilt/swivel/pivot adjustments to accommodate any desk</li><li>Exclusive GameVisual & GamePlus functions to enhance color performance and control</li><li>FreeSync/Adaptive Sync technology with 75 Hz refresh rate for a tear-free experience with AMD Radeon GPUs</li></ul>', 'available' => true),
array('quantity' => 10, 'productName' => 'Acer Chromebook 14, Aluminum, 14-inch Full HD, Intel Celeron N3160, 4GB LPDDR3, 32GB, Chrome, Gold, CB3-431-C0AK', 'category' => 'PC & Accessories', 'brand' => 'Acer', 'price' => '299.99', 'image' => 'C7O8YcIKxy.jpg', 'description' => '<ul><li>Intel Celeron N3160 Quad-Core Processor 1.6GHz with Intel Burst Technology up to 2.24GHz</li><li>14\" Full HD ComfyView Widescreen IPS LED-backlit Display</li><li>4GB LPDDR3 Onboard Memory, 32GB Internal Storage</li><li>Google Chrome Operating System</li><li>Up to 12-hours Battery Life</li></ul>', 'available' => true),
array('quantity' => 10, 'productName' => 'ASUS ROG SWIFT PG348Q 34\" 3440x1440 IPS 100Hz G-SYNC Eye Care Gaming Monitor', 'category' => 'PC & Accessories', 'brand' => 'Asus', 'price' => '1229.99', 'image' => '1HXNBkAx5h.jpg', 'description' => '<ul><li>34\" 1440p IPS panel with NVIDIA G-SYNC Technology and 100Hz Refresh Rate deliver superior resolution, color, and smoothness, maximizing immersion in games.</li><li>Curved Ultra-wide 21:9 Aspect Ratio maximizes immersion by expanding the display right to the peripherals of your vision</li><li>ASUS Eye Care technology lowers blue light and eliminates flickering. When coupled with ergonomics, gaming marathons just got a lot easier.</li><li>5-Way OSD Joystick delivers the most intuitive control scheme for a monitor, so you can access features such as ASUS Game Plus on-the-fly.</li><li>3 year warranty</li></ul>', 'available' => true),
array('quantity' => 10, 'productName' => 'D-Link DIR-879 AC1900 EXO Wi-Fi Router', 'category' => 'PC & Accessories', 'brand' => 'D-Link', 'price' => '149.95', 'image' => 'xkFFoydULS.jpg', 'description' => '<ul><li>High-power amplifiers (1000mW) - Wider coverage throughout your home</li><li>SmartConnect - Band steering automatically balances wireless devices among the two wireless bands</li><li>Smart Beam Forming - Dramatically enhances wireless signal strength and throughput</li><li>Dual Core Processor - Faster wireless speeds, improved coverage and reliable connections</li><li>Dual Band Wireless - Surf the internet on the 2.4GHz band while streaming HD on the 5GHz band</li><li>Built-in gigabit ports - Fast and reliable wired connections</li><li>Intelligent QoS - Device optimization delivers seamless performance for your applications</li><li>Eliminate dead zones - Full coverage to reach dead zone in home environment</li></ul>', 'available' => true),

		));
    }
}
